/**
 * @file phone-input.constants.ts
 * @module @stackra/ui/react/components/phone-input
 * @description Country calling codes and default country list for PhoneInput.
 */

import type { PhoneCountry } from './phone-input.interface';

// ============================================================================
// Calling Codes
// ============================================================================

/** Map of ISO 3166-1 alpha-2 codes to international calling codes. */
export const CALLING_CODES: Record<string, string> = {
  AF: '93',
  AL: '355',
  DZ: '213',
  AR: '54',
  AU: '61',
  AT: '43',
  BH: '973',
  BD: '880',
  BE: '32',
  BR: '55',
  CA: '1',
  CL: '56',
  CN: '86',
  CO: '57',
  HR: '385',
  CZ: '420',
  DK: '45',
  EG: '20',
  FI: '358',
  FR: '33',
  DE: '49',
  GR: '30',
  HK: '852',
  HU: '36',
  IN: '91',
  ID: '62',
  IQ: '964',
  IE: '353',
  IL: '972',
  IT: '39',
  JP: '81',
  JO: '962',
  KW: '965',
  LB: '961',
  MY: '60',
  MX: '52',
  MA: '212',
  NL: '31',
  NZ: '64',
  NG: '234',
  NO: '47',
  OM: '968',
  PK: '92',
  PS: '970',
  PE: '51',
  PH: '63',
  PL: '48',
  PT: '351',
  QA: '974',
  RO: '40',
  RU: '7',
  SA: '966',
  SG: '65',
  ZA: '27',
  KR: '82',
  ES: '34',
  SE: '46',
  CH: '41',
  TW: '886',
  TH: '66',
  TR: '90',
  AE: '971',
  GB: '44',
  US: '1',
  VN: '84',
  YE: '967',
};

// ============================================================================
// Default Country List
// ============================================================================

/** Default list of countries for the phone input picker. */
export const DEFAULT_COUNTRIES: PhoneCountry[] = [
  { code: 'US', callingCode: '1', name: 'United States' },
  { code: 'GB', callingCode: '44', name: 'United Kingdom' },
  { code: 'CA', callingCode: '1', name: 'Canada' },
  { code: 'AU', callingCode: '61', name: 'Australia' },
  { code: 'DE', callingCode: '49', name: 'Germany' },
  { code: 'FR', callingCode: '33', name: 'France' },
  { code: 'IT', callingCode: '39', name: 'Italy' },
  { code: 'ES', callingCode: '34', name: 'Spain' },
  { code: 'NL', callingCode: '31', name: 'Netherlands' },
  { code: 'BR', callingCode: '55', name: 'Brazil' },
  { code: 'IN', callingCode: '91', name: 'India' },
  { code: 'JP', callingCode: '81', name: 'Japan' },
  { code: 'CN', callingCode: '86', name: 'China' },
  { code: 'KR', callingCode: '82', name: 'South Korea' },
  { code: 'SA', callingCode: '966', name: 'Saudi Arabia' },
  { code: 'AE', callingCode: '971', name: 'United Arab Emirates' },
  { code: 'EG', callingCode: '20', name: 'Egypt' },
  { code: 'QA', callingCode: '974', name: 'Qatar' },
  { code: 'KW', callingCode: '965', name: 'Kuwait' },
  { code: 'BH', callingCode: '973', name: 'Bahrain' },
  { code: 'OM', callingCode: '968', name: 'Oman' },
  { code: 'JO', callingCode: '962', name: 'Jordan' },
  { code: 'LB', callingCode: '961', name: 'Lebanon' },
  { code: 'IQ', callingCode: '964', name: 'Iraq' },
  { code: 'PS', callingCode: '970', name: 'Palestine' },
  { code: 'MA', callingCode: '212', name: 'Morocco' },
  { code: 'MX', callingCode: '52', name: 'Mexico' },
  { code: 'AR', callingCode: '54', name: 'Argentina' },
  { code: 'TR', callingCode: '90', name: 'Turkey' },
  { code: 'PK', callingCode: '92', name: 'Pakistan' },
  { code: 'NG', callingCode: '234', name: 'Nigeria' },
  { code: 'ZA', callingCode: '27', name: 'South Africa' },
  { code: 'SG', callingCode: '65', name: 'Singapore' },
  { code: 'MY', callingCode: '60', name: 'Malaysia' },
  { code: 'TH', callingCode: '66', name: 'Thailand' },
  { code: 'PH', callingCode: '63', name: 'Philippines' },
  { code: 'ID', callingCode: '62', name: 'Indonesia' },
  { code: 'SE', callingCode: '46', name: 'Sweden' },
  { code: 'NO', callingCode: '47', name: 'Norway' },
  { code: 'DK', callingCode: '45', name: 'Denmark' },
  { code: 'FI', callingCode: '358', name: 'Finland' },
  { code: 'PL', callingCode: '48', name: 'Poland' },
  { code: 'CH', callingCode: '41', name: 'Switzerland' },
  { code: 'AT', callingCode: '43', name: 'Austria' },
  { code: 'IE', callingCode: '353', name: 'Ireland' },
  { code: 'PT', callingCode: '351', name: 'Portugal' },
  { code: 'NZ', callingCode: '64', name: 'New Zealand' },
];
